---
- name: Add service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: rabbitmq
        namespace: doosra-vpc
        labels:
          app: rabbitmq
          type: LoadBalancer
      spec:
        type: ClusterIP
        ports:
         - name: http
           protocol: TCP
           port: 15672
           targetPort: 15672
         - name: amqp
           protocol: TCP
           port: 5672
           targetPort: 5672
        selector:
          app: rabbitmq

- name: Add sts
  k8s:
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: rabbitmq
        namespace: doosra-vpc
      spec:
        serviceName: rabbitmq
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: rabbitmq
        template:
          metadata:
            labels:
              app: rabbitmq
          spec:
            serviceAccountName: rabbitmq
            terminationGracePeriodSeconds: 10
            containers:
              - name: rabbitmq-autocluster
                image: wancloudsinc/rabbitmq
                ports:
                  - name: http
                    protocol: TCP
                    containerPort: 15672
                  - name: amqp
                    protocol: TCP
                    containerPort: 5672
                livenessProbe:
                  exec:
                    command: ["rabbitmqctl", "status"]
                  initialDelaySeconds: 30
                  timeoutSeconds: 5
                readinessProbe:
                  exec:
                    command: ["rabbitmqctl", "status"]
                  initialDelaySeconds: 10
                  timeoutSeconds: 5
                imagePullPolicy: Always
                env:
                  - name: MY_POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: RABBITMQ_USE_LONGNAME
                    value: "true"
                  - name: RABBITMQ_NODENAME
                    value: "rabbit@$(MY_POD_IP)"
                  - name: AUTOCLUSTER_TYPE
                    value: "k8s"
                  - name: AUTOCLUSTER_DELAY
                    value: "10"
                  - name: K8S_ADDRESS_TYPE
                    value: "ip"
                  - name: AUTOCLUSTER_CLEANUP
                    value: "true"
                  - name: CLEANUP_WARN_ONLY
                    value: "false"
            imagePullSecrets:
              - name: docker-hub-secret
