apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.indeed.com
  namespace: doosra-vpc
spec:
  group: indeed.com
  names:
    kind: Rabbitmq
    listKind: RabbitmqList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
