---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-operator
  template:
    metadata:
      labels:
        name: rabbitmq-operator
    spec:
      serviceAccountName: rabbitmq-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "wancloudsinc/rabbitmq:operator"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "wancloudsinc/rabbitmq:operator"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rabbitmq-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      imagePullSecrets:
        - name: docker-hub-secret
      volumes:
        - name: runner
          emptyDir: {}
